GRAVITY = 9.8
DRAG = 2

NAIL_STRENGTH = math.pow(2, 10)
PLANK_STRENGTH = math.pow(2, 10)

-- PHYSYCS CO
PC_PLAYER = 2
PC_PLANK = 3
PC_COLUMN = 4
PC_PLATFORM = 5
PC_BUILDING = 6
PC_GIB = 7
PC_PLAYER_AREA = 8
PC_PLAYER_FLOOR_BOX = 9

-- DRAWING LAYERS
DL_BACKGROUND = 1
DL_COLUMN = 10
DL_BUILDING = 15
DL_PLATFORM = 20
DL_GIB = 25
DL_NAIL = 30
DL_PLAYER = 90
DL_GHOST = 95
DL_MOUSE = 100